# -*- coding: utf-8 -*-
"""health_srip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ayIueplobgoVohljGCeS9rmkUquysOz

##file info
"""

print('Displaying first 20 lines of Flow - 30-05-2024.txt:')
!head -n 10 '/content/Flow - 30-05-2024.txt'
print('\nDisplaying first 20 lines of Thorac - 30-05-2024.txt:')
!head -n 10 '/content/Thorac - 30-05-2024.txt'
print('\nDisplaying first 20 lines of SPO2 - 30-05-2024.txt:')
!head -n 10 '/content/SPO2 - 30-05-2024.txt'
print('\nDisplaying first 20 lines of Flow Events - 30-05-2024.txt:')
!head -n 10 '/content/Flow Events - 30-05-2024.txt'

"""## Converting into pandas dataframe

For thorac, SPO2 and flow events.
Correct parsing and seting as the index for time-series alignment, handling the different sampling rates (32 Hz for respiration, 4 Hz for SpO₂).

"""

import pandas as pd

# Define file paths
flow_file_path = '/content/Flow - 30-05-2024.txt'
thorac_file_path = '/content/Thorac - 30-05-2024.txt'
spo2_file_path = '/content/SPO2 - 30-05-2024.txt'

# Function for loading and preprocessing data
def into_dataframe(file_path):
    df = pd.read_csv(file_path, skiprows=7, delimiter=';', decimal=',', names=['Timestamp', 'Value'])
    # Parsing 'Timestamp' to datetime objects
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='%d.%m.%Y %H:%M:%S,%f')
    # Seting 'Timestamp' as DataFrame's index
    df = df.set_index('Timestamp')

    return df

# Loading file into DataFrame
df_flow = into_dataframe(flow_file_path)
df_thorac = into_dataframe(thorac_file_path)
df_spo2 = into_dataframe(spo2_file_path)

print("df_flow head:")
print(df_flow.head())
print("\ndf_flow info:")
df_flow.info()

print("\ndf_thorac head:")
print(df_thorac.head())
print("\ndf_thorac info:")
df_thorac.info()

print("\ndf_spo2 head:")
print(df_spo2.head())
print("\ndf_spo2 info:")
df_spo2.info()

"""## Flow Event File


"""

event_file_path = '/content/Flow Events - 30-05-2024.txt'

# Load event data
df_events = pd.read_csv(event_file_path,skiprows=6,delimiter=';',names=['Event_Duration_Raw', 'Duration_in_Seconds', 'Event_Type', 'Sleep_Stage'])

def parse_event_duration(row_raw):
    parts = row_raw.split('-')
    start_str = parts[0].strip()
    end_str = parts[1].strip()

    # Parse start time
    start_dt = pd.to_datetime(start_str, format='%d.%m.%Y %H:%M:%S,%f')

    # for end time: if it doesn't contain a date, then it's the same day as start date
    if '.' not in end_str:
        end_str = start_dt.strftime('%d.%m.%Y ') + end_str

    end_dt = pd.to_datetime(end_str, format='%d.%m.%Y %H:%M:%S,%f')

    return start_dt, end_dt

# Apply the parsing function to create Start_Time and End_Time
df_events[['Start_Time', 'End_Time']] = df_events['Event_Duration_Raw'].apply(lambda x: pd.Series(parse_event_duration(x)))

print("df_events head:")
print(df_events.head())
print("\ndf_events info:")
df_events.info()

"""### Combining Nasal Airflow, Thoracic Movement, and SpO2 into a single DataFrame with a common time index, and preparing event annotations for overlay.
Interpolating NaN values in the 'SPO2' column for handling the difference in sampling rates.
"""

import pandas as pd

df_flow = df_flow.rename(columns={'Value': 'Flow'})
df_thorac = df_thorac.rename(columns={'Value': 'Thorac'})
df_spo2 = df_spo2.rename(columns={'Value': 'SPO2'})

# combining thorac and flow
df_respiration_signals = pd.merge(df_flow, df_thorac, left_index=True, right_index=True, how='outer')
# combining again :) upar wale and sp02
df_all_signals = pd.merge(df_respiration_signals, df_spo2, left_index=True, right_index=True, how='outer')

# linear interpolation to fill null values, to preserve overall trend and make signal smooth
df_all_signals['SPO2'] = df_all_signals['SPO2'].interpolate(method='linear')

# 7. Display the first few rows and a summary of the DataFrame's information for df_all_signals
print("df_all_signals head:")
print(df_all_signals.head())
print("\ndf_all_signals info:")
df_all_signals.info()

"""## Generate Visualizations


"""

import matplotlib.pyplot as plt
import pandas as pd

# padding before and after event (in seconds)
padding = pd.Timedelta(seconds=30)

for i, row in df_events.iterrows():

    start_time = row['Start_Time']
    end_time = row['End_Time']

    window_start = start_time - padding
    window_end = end_time + padding

    # Slice signal data for that window
    df_window = df_all_signals.loc[window_start:window_end]

    # Create figure
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, sharex=True, figsize=(15, 8))

    # Plot airflow
    ax1.plot(df_window.index, df_window['Flow'], color='blue')
    ax1.set_ylabel('Nasal Airflow')
    ax1.grid(True)

    # Plot thoracic movement
    ax2.plot(df_window.index, df_window['Thorac'], color='orange')
    ax2.set_ylabel('Thoracic Movement')
    ax2.grid(True)

    # Plot SpO2
    ax3.plot(df_window.index, df_window['SPO2'], color='green')
    ax3.set_ylabel('SpO₂')
    ax3.grid(True)

    # Overlay event
    ax1.axvspan(start_time, end_time, color='red', alpha=0.3)
    ax2.axvspan(start_time, end_time, color='red', alpha=0.3)
    ax3.axvspan(start_time, end_time, color='red', alpha=0.3)

    fig.suptitle(f"Event {i+1}: {start_time} to {end_time}", fontsize=14)
    plt.tight_layout()
    plt.show()

"""## Save as PDF

"""

import os

output_dir = 'Visualizations'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

output_pdf_path = os.path.join(output_dir, 'physiological_signals_and_events.pdf')

fig.savefig(output_pdf_path, bbox_inches='tight')

print(f"Visualization saved as {output_pdf_path}")

"""## Create vis.py Script

**Reasoning**:
I need to create a Python script named `vis.py` that encapsulates all the data loading, processing, plotting, and saving logic based on the previous steps. This will involve defining functions, hardcoding file paths for now, and then executing the data manipulation and visualization code to save a PDF.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vis.py
# import pandas as pd
# import matplotlib.pyplot as plt
# from matplotlib.backends.backend_pdf import PdfPages
# import os
# 
# # Function to load and preprocess physiological data
# def into_dataframe(file_path):
#     df = pd.read_csv(file_path,skiprows=7,delimiter=';',decimal=',',names=['Timestamp', 'Value'])
#     df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='%d.%m.%Y %H:%M:%S,%f')
#     df = df.set_index('Timestamp')
#     return df
# 
# # Function to parse event duration strings into start and end datetime objects
# def parse_event_duration(row_raw):
#     parts = row_raw.split('-')
#     start_str = parts[0].strip()
#     end_str = parts[1].strip()
#     start_dt = pd.to_datetime(start_str, format='%d.%m.%Y %H:%M:%S,%f')
#     if '.' not in end_str:
#         end_str = start_dt.strftime('%d.%m.%Y ') + end_str
#     end_dt = pd.to_datetime(end_str, format='%d.%m.%Y %H:%M:%S,%f')
# 
#     return start_dt, end_dt
# 
# # Main execution block
# if __name__ == "__main__":
#     # hardcoded file paths
#     flow_file_path = '/content/Flow - 30-05-2024.txt'
#     thorac_file_path = '/content/Thorac - 30-05-2024.txt'
#     spo2_file_path = '/content/SPO2 - 30-05-2024.txt'
#     event_file_path = '/content/Flow Events - 30-05-2024.txt'
# 
#     # physiological signal file into a DataFrame
#     df_flow = into_dataframe(flow_file_path)
#     df_thorac = into_dataframe(thorac_file_path)
#     df_spo2 = into_dataframe(spo2_file_path)
# 
#     # event data
#     df_events = pd.read_csv(event_file_path, skiprows=6, delimiter=';', names=['Event_Duration_Raw', 'Duration_in_Seconds', 'Event_Type', 'Sleep_Stage'])
# 
#     # createing Start_Time and End_Time for events
#     df_events[['Start_Time', 'End_Time']] = df_events['Event_Duration_Raw'].apply(lambda x: pd.Series(parse_event_duration(x)))
# 
#     # Rename'Value' column
#     df_flow = df_flow.rename(columns={'Value': 'Flow'})
#     df_thorac = df_thorac.rename(columns={'Value': 'Thorac'})
#     df_spo2 = df_spo2.rename(columns={'Value': 'SPO2'})
# 
#     # combining
#     df_respiration_signals = pd.merge(df_flow, df_thorac, left_index=True, right_index=True, how='outer')
#     df_all_signals = pd.merge(df_respiration_signals, df_spo2, left_index=True, right_index=True, how='outer')
#     df_all_signals['SPO2'] = df_all_signals['SPO2'].interpolate(method='linear')
# 
#     window_duration = pd.Timedelta(minutes=5)
# 
#     start_time = df_all_signals.index.min()
#     end_time = df_all_signals.index.max()
# 
#     current_start = start_time
#     window_count = 1
# 
#     output_dir = 'Visualizations'
#     if not os.path.exists(output_dir):
#         os.makedirs(output_dir)
# 
#     output_pdf_path = os.path.join(output_dir, 'full_night_visualization.pdf')
# 
#     with PdfPages(output_pdf_path) as pdf:
# 
#         while current_start < end_time:
# 
#             current_end = current_start + window_duration
#             df_window = df_all_signals.loc[current_start:current_end]
# 
#             if df_window.empty:
#                 current_start = current_end
#                 continue
# 
#             fig, (ax1, ax2, ax3) = plt.subplots(3, 1, sharex=True, figsize=(15, 8))
# 
#             # Flow
#             ax1.plot(df_window.index, df_window['Flow'], color='blue', linewidth=1)
#             ax1.set_ylabel('Nasal Airflow')
#             ax1.grid(True)
# 
#             # Thoracic
#             ax2.plot(df_window.index, df_window['Thorac'], color='orange', linewidth=1)
#             ax2.set_ylabel('Thoracic Movement')
#             ax2.grid(True)
# 
#             # SPO2
#             ax3.plot(df_window.index, df_window['SPO2'], color='green', linewidth=1)
#             ax3.set_ylabel('SpO₂')
#             ax3.grid(True)
# 
#             # Overlay events in this window
#                         # Overlay events in this window with different colors
#             for _, row in df_events.iterrows():
# 
#                 event_start = row['Start_Time']
#                 event_end = row['End_Time']
#                 event_type = row['Event_Type']
# 
#                 if event_start <= current_end and event_end >= current_start:
# 
#                     # Choose color based on event type
#                     if 'Apnea' in event_type:
#                         color = 'red'
#                     elif 'Hypopnea' in event_type:
#                         color = 'orange'
#                     else:
#                         color = 'purple'
# 
#                     # Shade event region
#                     ax1.axvspan(event_start, event_end, color=color, alpha=0.3)
#                     ax2.axvspan(event_start, event_end, color=color, alpha=0.3)
#                     ax3.axvspan(event_start, event_end, color=color, alpha=0.3)
# 
#                     # Add event label on top subplot
#                     ax1.text(
#                         event_start,
#                         ax1.get_ylim()[1] * 0.9,
#                         event_type,
#                         color=color,
#                         fontsize=8,
#                         verticalalignment='top'
#                     )
# 
#             fig.suptitle(
#                 f"Window {window_count}\n{current_start} to {current_end}",
#                 fontsize=12
#             )
# 
#             plt.tight_layout(rect=[0, 0.03, 1, 0.95])
# 
#             pdf.savefig(fig)
#             plt.close(fig)
# 
#             window_count += 1
#             current_start = current_end
# 
# 
#     print(f"Visualization saved as {output_pdf_path}")
#

"""## To test the vis.py script, execute it from the command line using "!python vis.py".


"""

print('Running vis.py script:')
!python vis.py

"""## Dynamic file input


"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vis.py
# import pandas as pd
# import matplotlib.pyplot as plt
# import os
# import argparse
# 
# #physiological data
# def load_dataframe(file_path):
#     df = pd.read_csv(file_path,skiprows=7,delimiter=';',decimal=',',names=['Timestamp', 'Value'])
#     df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='%d.%m.%Y %H:%M:%S,%f')
#     df = df.set_index('Timestamp')
# 
#     return df
# 
# def parse_event_duration(row_raw):
#     parts = row_raw.split('-')
#     start_str = parts[0].strip()
#     end_str = parts[1].strip()
#     start_dt = pd.to_datetime(start_str, format='%d.%m.%Y %H:%M:%S,%f')
#     if '.' not in end_str:
#         end_str = start_dt.strftime('%d.%m.%Y ') + end_str
#     end_dt = pd.to_datetime(end_str, format='%d.%m.%Y %H:%M:%S,%f')
#     return start_dt, end_dt
# 
# # Main block
# if __name__ == "__main__":
#     parser = argparse.ArgumentParser(description='Generate physiological signal and event visualizations.')
#     parser.add_argument('--folder_path', type=str, required=True,
#                         help='Path to the participant folder containing data files.')
#     args = parser.parse_args()
# 
#     # Define dynamic file paths
#     flow_file_path = os.path.join(args.folder_path, 'Flow - 30-05-2024.txt')
#     thorac_file_path = os.path.join(args.folder_path, 'Thorac - 30-05-2024.txt')
#     spo2_file_path = os.path.join(args.folder_path, 'SPO2 - 30-05-2024.txt')
#     event_file_path = os.path.join(args.folder_path, 'Flow Events - 30-05-2024.txt')
# 
#     #physiological data
#     df_flow = load_dataframe(flow_file_path)
#     df_thorac = load_dataframe(thorac_file_path)
#     df_spo2 = load_dataframe(spo2_file_path)
# 
#     #event data
#     df_events = pd.read_csv(event_file_path,skiprows=6,delimiter=';', names=['Event_Duration_Raw', 'Duration_in_Seconds', 'Event_Type', 'Sleep_Stage'])
# 
#     df_events[['Start_Time', 'End_Time']] = df_events['Event_Duration_Raw'].apply(lambda x: pd.Series(parse_event_duration(x)))
# 
#     # Rename 'Value'
#     df_flow = df_flow.rename(columns={'Value': 'Flow'})
#     df_thorac = df_thorac.rename(columns={'Value': 'Thorac'})
#     df_spo2 = df_spo2.rename(columns={'Value': 'SPO2'})
# 
#     #Combining
#     df_respiration_signals = pd.merge(df_flow, df_thorac, left_index=True, right_index=True, how='outer')
#     df_all_signals = pd.merge(df_respiration_signals, df_spo2, left_index=True, right_index=True, how='outer')
#     df_all_signals['SPO2'] = df_all_signals['SPO2'].interpolate(method='linear')
# 
#     from matplotlib.backends.backend_pdf import PdfPages
#     from matplotlib.patches import Patch
# 
#     window_duration = pd.Timedelta(minutes=5)
# 
#     start_time = df_all_signals.index.min()
#     end_time = df_all_signals.index.max()
# 
#     current_start = start_time
#     window_count = 1
# 
#     output_dir = 'Visualizations'
#     if not os.path.exists(output_dir):
#         os.makedirs(output_dir)
# 
#     output_pdf_path = os.path.join(output_dir, f'{participant_name}_visualization.pdf')
# 
#     with PdfPages(output_pdf_path) as pdf:
# 
#         while current_start < end_time:
# 
#             current_end = current_start + window_duration
#             df_window = df_all_signals.loc[current_start:current_end]
# 
#             if df_window.empty:
#                 current_start = current_end
#                 continue
# 
#             fig, (ax1, ax2, ax3) = plt.subplots(3, 1, sharex=True, figsize=(15, 8))
# 
#             # Plot Flow
#             ax1.plot(df_window.index, df_window['Flow'], color='blue', linewidth=1)
#             ax1.set_ylabel('Nasal Airflow')
#             ax1.grid(True)
# 
#             # Plot Thoracic
#             ax2.plot(df_window.index, df_window['Thorac'], color='orange', linewidth=1)
#             ax2.set_ylabel('Thoracic Movement')
#             ax2.grid(True)
# 
#             # Plot SPO2
#             ax3.plot(df_window.index, df_window['SPO2'], color='green', linewidth=1)
#             ax3.set_ylabel('SpO₂')
#             ax3.grid(True)
# 
#             # Add legend for event types
#             legend_elements = [
#                 Patch(facecolor='red', alpha=0.3, label='Apnea'),
#                 Patch(facecolor='orange', alpha=0.3, label='Hypopnea')
#             ]
#             ax1.legend(handles=legend_elements)
# 
#             # Overlay events in this window
#             for _, row in df_events.iterrows():
# 
#                 event_start = row['Start_Time']
#                 event_end = row['End_Time']
#                 event_type = str(row['Event_Type'])
# 
#                 if event_start <= current_end and event_end >= current_start:
# 
#                     # Color coding
#                     if 'Apnea' in event_type:
#                         color = 'red'
#                     elif 'Hypopnea' in event_type:
#                         color = 'orange'
#                     else:
#                         color = 'purple'
# 
#                     ax1.axvspan(event_start, event_end, color=color, alpha=0.3)
#                     ax2.axvspan(event_start, event_end, color=color, alpha=0.3)
#                     ax3.axvspan(event_start, event_end, color=color, alpha=0.3)
# 
#                     # Add label on airflow subplot
#                     ax1.text(
#                         event_start,
#                         ax1.get_ylim()[1] * 0.9,
#                         event_type,
#                         color=color,
#                         fontsize=7,
#                         verticalalignment='top'
#                     )
# 
#             fig.suptitle(
#                 f"Window {window_count}\n{current_start} to {current_end}",
#                 fontsize=12
#             )
# 
#             plt.tight_layout(rect=[0, 0.03, 1, 0.95])
# 
#             pdf.savefig(fig)
#             plt.close(fig)
# 
#             window_count += 1
#             current_start = current_end
# 
#     print(f"Visualization saved as {output_pdf_path}")
# 
#     # Optionally display the plot (if running in an interactive environment)
#     # plt.show()

print('Running vis.py script with --folder_path /content:')
!python vis.py --folder_path /content
